version: '{build}'
os: Visual Studio 2015
configuration: Release
build:
  project: Nest.Indexify.sln
  verbosity: minimal
after_build:
  cmd: nuget pack src/Nest.Indexify/Nest.Indexify.csproj -Version %GitVersion_NugetVersion% -IncludeReferencedProjects -Properties "Configuration=%CONFIGURATION%" -Verbosity quiet
artifacts:
- path: Nest.Indexify.*.nupkg
cache: packages -> src\packages.config